{
 "title": "Film_Store",
 "time": { "from": "2005-05-24T00:00:00.000Z", "to": "2006-02-14T00:00:00.000Z" },
 "panels": [
  {
   "title": "Rentas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ranking con las 10 películas más rentadas",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT f.title AS pelicula, COUNT(*) AS total_rentas\nFROM public.rental r\nJOIN public.inventory i ON r.inventory_id = i.inventory_id\nJOIN public.film f ON i.film_id = f.film_id\nGROUP BY pelicula\nORDER BY total_rentas DESC\nLIMIT 10;"
      }
     ]
    },
    {
     "title": "Total Rentas",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS total_rentas FROM rental;"
      }
     ]
    },
    {
     "title": "Total de rentas por dia",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT DATE(rental_date) AS fecha, COUNT(*) AS total_rentas\nFROM public.rental\nGROUP BY fecha\nORDER BY fecha;\n"
      }
     ]
    },
    {
     "title": "Cantidad de rentas por categoría de los filmes",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT c.name AS categoria, COUNT(*) AS total_rentas\nFROM public.rental r\nJOIN public.inventory i ON r.inventory_id = i.inventory_id\nJOIN public.film_category fc ON i.film_id = fc.film_id\nJOIN public.category c ON fc.category_id = c.category_id\nGROUP BY categoria\nORDER BY total_rentas DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cantidad Clientes x Paises",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT c.country, COUNT(*) AS cantidad_clientes\nFROM public.customer cu\nJOIN public.address a ON cu.address_id = a.address_id\nJOIN public.city ci ON a.city_id = ci.city_id\nJOIN public.country c ON ci.country_id = c.country_id\nGROUP BY c.country;"
      }
     ]
    },
    {
     "title": "Total de clientes",
     "type": "stat",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS total_clientes FROM public.customer;"
      }
     ]
    },
    {
     "title": " Ranking con los 10 clientes que menos pagan durante las rentas de películas",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT cu.first_name, cu.last_name, SUM(p.amount) AS total_pagado\nFROM public.customer cu\nJOIN public.payment p ON cu.customer_id = p.customer_id\nGROUP BY cu.customer_id, cu.first_name, cu.last_name\nORDER BY total_pagado ASC\nLIMIT 10;"
      }
     ]
    },
    {
     "title": "Ranking con los 10 clientes que más películas rentan",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT cu.first_name, cu.last_name, COUNT(*) AS cantidad_rentas\nFROM public.customer cu\nJOIN rental r ON cu.customer_id = r.customer_id\nGROUP BY cu.first_name, cu.last_name\nORDER BY cantidad_rentas DESC\nLIMIT 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "Films",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total de Peliculas",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) as cantidad_peliculas from film"
      }
     ]
    },
    {
     "title": "Cantidad de peliculas por categoria",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT c.name AS category, COUNT(*) AS movie_count\nFROM film_category fc\nJOIN category c ON fc.category_id = c.category_id\nGROUP BY c.name;"
      }
     ]
    },
    {
     "title": "Costo de repuesto por Pelicula",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT title, replacement_cost\nFROM film\nORDER BY replacement_cost DESC;"
      }
     ]
    },
    {
     "title": "Cantidad de peliculas por Rating",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT rating, COUNT(*) AS cantidad_peliculas\nFROM film\nGROUP BY rating;"
      }
     ]
    }
   ]
  }
 ]
}